import { Question } from "@prisma/client";
import { db } from "../db.server";

export type QuestionWithDetails = Question & {

}

export async function createQuestion(        
        groupId: string,
        questionClassId: number,
        qBody: string,
        qImageUrl: string,
        qDetails: string,
        qSummary: string,
        qExternalLink: string,
        isAccepted: boolean
        ) {

    return await db.question.create({
        data: {
            // id generated by db
            // createdAt autogenerated by db
            groupId,
            questionClassId,
            
            qBody,
            qImageUrl,
            qDetails,
            qSummary,
            qExternalLink,
            isAccepted
        }
    })
}

export async function getQuestionsByClass(id: any) {
    const questionClassId = Number(id);
    return await db.question.findMany(
        {
            where: {
                questionClassId
            }
        }
    )
}

